[general]
import = [
    "~/.config/alacritty/themes/themes/duskfox.toml"
]

[window]
padding = { x = 4, y = 2 }
opacity = 0.75
blur = true

[scrolling]
multiplier = 5

[font]
normal = { family = "Mint Mono", style = "Regular" }
bold = { family = "Mint Mono", style = "Bold" }
italic = { family = "Mint Mono", style = "Italic" }
bold_italic = { family = "Mint Mono", style = "Bold Italic" }
size = 12.0
offset = { x = 2, y = 4 }
fallbacks = ["Hack Nerd Font"]

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux"] }
