[general]
# import = [
#     "~/.config/alacritty/themes/themes/ayu_mirage.toml"
# ]

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
opacity = 0.9
blur = true
decorations = "Full"

[scrolling]
multiplier = 5

[font]
normal = { family = "Mint Mono", style = "Regular" }
bold = { family = "Mint Mono", style = "Bold" }
italic = { family = "Mint Mono", style = "Italic" }
bold_italic = { family = "Mint Mono", style = "Bold Italic" }
size = 14.0
offset = { x = 4, y = 8 }

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux"] }

# Kanso Mist Alacritty Colors

[colors.primary]
background = '#22262D'
foreground = '#C5C9C7'

[colors.normal]
black = '#22262D'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#a292a3'
cyan = '#8ea4a2'
white = '#a4a7a4'

[colors.bright]
black = '#5C6066'
red = '#e46876'
green = '#87a987'
yellow = '#e6c384'
blue = '#7fb4ca'
magenta = '#938aa9'
cyan = '#7aa89f'
white = '#C5C9C7'

[colors.selection]
background = '#43464E'
foreground = '#C5C9C7'

[[colors.indexed_colors]]
index = 16
color = '#b6927b'

[[colors.indexed_colors]]
index = 17
color = '#b98d7b'